#!/bin/sh
LIST_OF_APPS="chromium visual-studio-code"

YAOURT_CMD=$(which yaourt)
APT_GET_CMD=$(which apt-get)

if [[ ! -z $APT_GET_CMD ]]; then
    yaourt -Sy
    yaourt -S $LIST_OF_APPS
elif [[ ! -z $APT_GET_CMD ]]; then
    sudo apt-get update
    apt-get $LIST_OF_APPS
else
    echo "error can't install package $PACKAGE"
    exit 1;
fi

